[build]
  publish = "sites/clientes/academia-mestre-sandro/site"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
